### PR TITLE
🐛  (kustomize/v2,go/v4): fix kustomization yaml's webhooks patches file names for multgroup layouts

### LINKED ISSUE #3502: Inconsistent CRD webhook and certmanager patches kustomization for multigroup go/v4 projects
### What broke? What's expected?

Due to a bug in multigroup Kubebuilder projects with the layout go/v4, manifest patches in `config/crd/patches` got names with suffixes `group_kind`, but the `config/crd/kustomization.yaml` references them wrong, as names with suffixes `kind`.

How to reproduce:

Create a tutorial project, make it multygroup, create a new API as https://book.kubebuilder.io/cronjob-tutorial/new-api.html. I don't sure that need to call `make manifests` or not.

You should have these files in patches:

```sh
$ tree config/crd/patches/
config/crd/patches/
├── cainjection_in_batch_cronjobs.yaml
└── webhook_in_batch_cronjobs.yaml

0 directories, 2 files
```

But the `config/crd/kustomization.yaml` references them wrong, as names with suffixes `kind`.

```sh
$ grep "path" config/crd/kustomization.yaml 
#- path: patches/webhook_in_cronjobs.yaml
#- path: patches/cainjection_in_cronjobs.yaml
```

The first name should be the `patches/webhook_in_`**batch_**`cronjobs.yaml`. 

### Reproducing this issue

Create a tutorial project, make it multygroup, create a new API as https://book.kubebuilder.io/cronjob-tutorial/new-api.html. I don't sure that need to call `make manifests` or not.
```sh
denis@L560:~/huma$ mkdir project
denis@L560:~/huma$ cd project/
denis@L560:~/huma/project$ kubebuilder init --domain tutorial.kubebuilder.io --repo tutorial.kubebuilder.io/project
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.15.0
Update dependencies:
$ go mod tidy
Next: define a resource with:
$ kubebuilder create api
denis@L560:~/huma/project$ kubebuilder version
Version: main.version{KubeBuilderVersion:"3.11.1", KubernetesVendor:"1.27.1", GitCommit:"1dc8ed95f7cc55fef3151f749d3d541bec3423c9", BuildDate:"2023-07-03T13:10:56Z", GoOs:"linux", GoArch:"amd64"}
denis@L560:~/huma/project$ kubebuilder edit --multigroup=true
denis@L560:~/huma/project$ kubebuilder create api --group batch --version v1 --kind CronJob
Create Resource [y/n]
y
Create Controller [y/n]
y
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
api/batch/v1/cronjob_types.go
api/batch/v1/groupversion_info.go
internal/controller/batch/suite_test.go
internal/controller/batch/cronjob_controller.go
Update dependencies:
$ go mod tidy
Running make:
$ make generate
mkdir -p /home/denis/huma/project/bin
test -s /home/denis/huma/project/bin/controller-gen && /home/denis/huma/project/bin/controller-gen --version | grep -q v0.12.0 || \
GOBIN=/home/denis/huma/project/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.12.0
/home/denis/huma/project/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
Next: implement your new API and generate the manifests (e.g. CRDs,CRs) with:
$ make manifests
denis@L560:~/huma/project$ make manifests 
/home/denis/huma/project/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
$ tree config/crd/patches/
config/crd/patches/
├── cainjection_in_batch_cronjobs.yaml
└── webhook_in_batch_cronjobs.yaml

0 directories, 2 files
$ grep "path" config/crd/kustomization.yaml 
#- path: patches/webhook_in_cronjobs.yaml
#- path: patches/cainjection_in_cronjobs.yaml
```

### KubeBuilder (CLI) Version

3.11.1

### PROJECT version

3

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v4
```

### Other versions

$ go version
go version go1.20.5 linux/amd64
$ bin/controller-gen --version
Version: v0.12.0
controller-runtime@v0.15.0

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by lowang-bh**
Fixes #3502

The comments about path of patch file name in `config/crd/kustomization.yaml` is not correct when enable multigroup

make test passed.
image

### CODE REVIEW

File: pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/kustomization.go [hunk 1]
```diff
@@ -68,9 +68,9 @@ func (f *Kustomization) GetMarkers() []machinery.Marker {
 const (
 	resourceCodeFragment = `- bases/%s_%s.yaml
```
Comment (camilamacedo86) [inline pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/kustomization.go:69]: Thank you for the contribution

The kustomize/v1 is only used in the deprecated layouts
It is deprecated as well.

So, we should only fix it in the kustomize/v2

Could you please remove the change from this file?

**Review by camilamacedo86 — CHANGES_REQUESTED** [review]
Thank you for the contribution 🥇 

Just a few nits:

- We should only change kustomize/v2 ( v1 is deprecated )
- We need to run make generate after the changes so that the samples are updated
- Please, ensure that after the changes you have only one commit ( squash them out ) so that we can get it merged

PS.: Note that I changed the title for we have a better info for the release notes. I hope that you do not mind.

**Comment by lowang-bh** [comment]
> Just a few nits:
> 
> * We should only change kustomize/v2 ( v1 is deprecated )
> * We need to run make generate after the changes so that the samples are updated
> * Please, ensure that after the changes you have only one commit ( squash them out ) so that we can get it merged

Got it.

**Review by camilamacedo86 — APPROVED** [review]
Great 👍 

I am happy that you check that we should only use the group in the name for multi-group layouts.

**Review by camilamacedo86 — COMMENTED** [review]
/lgtm
