### PR TITLE
:bug: Add external plugin arg filter funcs and add filters for "--group", "--version", "--kind"

### LINKED ISSUE #2809: (Phase 2 Plugins): external plugin will rebind `--group`, `--version`, `--kind` flags
### What broke? What's expected?

When running `kubebuilder create api` or `kubebuilder create webhook` with the `--plugins` flag set to use an external plugin, the external plugin flag binding logic will attempt to rebind the `--group`, `--version`, and `--kind` flags. These flags are already bound automatically by Kubebuilder.

The external plugin flag binding logic needs to be modified to ensure that we do NOT attempt to bind any flags that kubebuilder has already bound. This would likely need to be done here:
https://github.com/kubernetes-sigs/kubebuilder/blob/95f55fcf8b87397f7fdf97456b10ff70b31f728e/pkg/plugins/external/helpers.go#L158-L178

and here:
https://github.com/kubernetes-sigs/kubebuilder/blob/95f55fcf8b87397f7fdf97456b10ff70b31f728e/pkg/plugins/external/helpers.go#L180-L198

### Reproducing this issue

It is not trivial to reproduce this issue, and I only encountered it when creating a sample Phase 2 Plugin that can be used for e2e testing the Phase 2 Plugins implementation.

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"v3.5.0-46-g60d0c6ee-dirty", KubernetesVendor:"unknown", GitCommit:"60d0c6ee9eeb1c07dee1eed88ba4004362ec42a7", BuildDate:"2022-07-06T20:56:11Z", GoOs:"linux", GoArch:"amd64"}

### PROJECT version

_No response_

### Plugin versions

_No response_

### Other versions

Go: go version go1.18.3 linux/amd64

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by jakobmoellersap**
This fixes #2809 by introducing filter functions for plugin arguments. It currently includes two filter functions, one for the already existing implicit filter of "--help" and one for the GVK filter with "--group", "--version", "--kind". It is an arbitrary filter function so it can later on also support other filter requirements if necessary.

Tests are adjusted, but I added some tests for the filter functions. The existing helper Test for the Binding of Args I expanded to make use of the filter Functions as this is the use case in the actual method call in the CLI.

### CODE REVIEW

**Comment by everettraven** [comment]
@jakobmoellersap Thanks for the contribution! 

I took a quick glance and this looks great but I'd like to dig into this a little deeper. In the meantime I will approve the tests.

/ok-to-test

**Comment by camilamacedo86** [comment]
/ok-to-test

The code shows fine. But for this one, I would like to ask @everettraven and @rashmigottipati to give it a look since they were more involved with it.

File: pkg/plugins/external/external_test.go [hunk 1]
```diff
@@ -498,6 +543,11 @@ var _ = Describe("Run external plugin using Scaffold", func() {
 				Expect(fs.Lookup(flag.Name).Usage).To(Equal(flag.Usage))
 				Expect(fs.Lookup(flag.Name).DefValue).To(Equal(flag.Default))
 			}
+
+			By("bindAllFlags not have bound any forbidden flag after filtering")
```
Comment (everettraven) [inline pkg/plugins/external/external_test.go:547]: Minor nit:
```suggestion
			By("bindSpecificFlags not have bound any forbidden flag after filtering")
```

**Review by everettraven — CHANGES_REQUESTED** [review]
Just a really minor nit in the test that should be fixed so there isn't any confusion if the test case fails. 

Other than that it looks great! Thanks @jakobmoellersap !

**Review by everettraven — APPROVED** [review]
Looks great! I love how it is built to be easy to extend in the future! Awesome job @jakobmoellersap !

**Comment by jakobmoellersap** [comment]
Blocked by https://github.com/kubernetes-sigs/kubebuilder/issues/2878

**Comment by everettraven** [comment]
@jakobmoellersap #2879 was merged. If you rebase with master it should kick off the checks again with the updated action.

**Review by everettraven — COMMENTED** [review]
/lgtm

**Comment by everettraven** [comment]
@jakobmoellersap I'm not an approver so I can't add the approved label. 

@camilamacedo86 would you mind giving this another look?

/cc @camilamacedo86

**Review by camilamacedo86 — APPROVED** [review]
I think we can move with this one

/approved
