### PR TITLE
🐛 (alpha generate command): Ensure kubebuilder reuses its own binary instead of relying on $PATH

### LINKED ISSUE #4900: kubebuilder alpha generate calls kubebuilder cmd from path instead of it's own
### What broke? What's expected?

When running `kubebuilder alpha generate`, the generate-subcommand is directly invoking the `kubebuilder` binary in the current working directory.

This might lead to a failed execution in two different ways:
* your `kubebuilder` binary is not in `PATH` and you want to run the binary from somewhere else
```
$ /tmp/kubebuilder alpha generate
Error: kubebuilder not found in the path: exec: "kubebuilder": executable file not found in $PATH
Usage:
  kubebuilder alpha generate [flags]

Flags:
  -h, --help                help for generate
      --input-dir string    Specifies the full path to a Kubebuilder project file. If not provided, the current working directory is used.
      --output-dir string   Specifies the full path where the scaffolded files will be output. Defaults to a directory within the current working directory.

Global Flags:
      --plugins strings   plugin keys to be used for this subcommand execution

FATA error executing command: kubebuilder not found in the path: exec: "kubebuilder": executable file not found in $PATH 
```

* the version of `kubebuilder` in `PATH` is an older one where `kubebuilder alpha generate` is getting called (where e.g. not all plugins already exist - e.g. the newly introduced helm plugin)

Within `alpha generate` there is a check to verify if `kubebuilder` is in PATH:
`exec.LookPath` func from https://github.com/kubernetes-sigs/kubebuilder/blob/1f774a58c891f18d141058628a31ba96f4c24263/pkg/cli/alpha/internal/generate.go#L146

and than `kubebuilder` is getting called via `RunCmd("kubebuilder`:
https://github.com/search?q=repo%3Akubernetes-sigs%2Fkubebuilder+util.RunCmd%28%22kubebuilder+path%3Apkg%2Fcli%2Falpha%2Finternal%2F*&type=code

*additional notes:*
at least for Linux it could get solved by using the value of the `_` environment variable (e.g.: `os.Getenv("_")` )

### Reproducing this issue

1. ensure `kubebuilder` is not in your `PATH`
2. move `kubebuilder` binary to e.g. `/tmp`
3. change your working dir to an existing `kubebuilder` generated directory
4. run `/tmp/kubebuilder alpha generate`

### KubeBuilder (CLI) Version

4.6.0

### PROJECT version

3

### Plugin versions

```yaml

```

### Other versions

_No response_

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by ashishkpathak-connect**
Fix Kubebuilder executable path not found for `kubebuilder alpha generate` command.

Fixes #4900

### CODE REVIEW

**Comment by ashishkpathak-connect** [comment]
Upon checking os.Executable() api, I found that it has a support for darwin too. Details at https://cs.opensource.google/go/go/+/refs/tags/go1.25.1:src/os/executable_darwin.go

So, I used os.Executable to ensure the binary "kubebuilder" which was invoked to call `kubebuilder alpha generate` is the one which calls `kubebuilder init`.

**Comment by ashishkpathak-connect** [comment]
> Upon checking os.Executable() api, I found that it has a support for darwin too. Details at https://cs.opensource.google/go/go/+/refs/tags/go1.25.1:src/os/executable_darwin.go
> 
> So, I used os.Executable to ensure the binary "kubebuilder" which was invoked to call `kubebuilder alpha generate` is the one which calls `kubebuilder init`.

Below Test shows kubebuilder executable was correctly invoked even though it didn't not exist in PATH.

bash-3.2$ which kubebuilder
bash-3.2$ echo $?
1
bash-3.2$ basename `pwd`
test4
bash-3.2$ ~/opensource2/kubebuilder/bin/kubebuilder alpha generate
WARN Using current working directory to re-scaffold the project 
WARN This directory will be cleaned up and all files removed before the re-generation 
INFO Cleaning directory dir=<DATA MASKED:Ashish>
INFO Running cleanup 
INFO Running cleanup 
INFO kubebuilder init 
INFO Writing kustomize manifests for you to edit... 
INFO Writing scaffold for you to edit... 
INFO Get controller runtime 
INFO Update dependencies

File: pkg/cli/alpha/internal/generate.go [hunk 1]
```diff
@@ -144,14 +144,31 @@ func (opts *Generate) Validate() error {
...
+
+	realPath, err := filepath.EvalSymlinks(execPath)
+	if err != nil {
+		slog.Warn("Unable to resolve symbolic link", "execPath", execPath, "error", err)
+		// Fallback to execPath
+		return execPath, nil
+	}
+
+	return realPath, nil
+}
```
Comment (camilamacedo86) [inline pkg/cli/alpha/internal/generate.go:170]: Will it work fine for Mac os as well?

Comment (ashishkpathak-connect) [reply pkg/cli/alpha/internal/generate.go:170]: Yes Camila. Below is a test from Mac os which shows it worked successfully:

```
bash-3.2$ sw_vers | head -n 2
ProductName:            macOS
ProductVersion:         15.6.1
bash-3.2$ basename `pwd`
test4
bash-3.2$ which kubebuilder
bash-3.2$ echo $?
1
bash-3.2$ ~/opensource2/kubebuilder/bin/kubebuilder alpha generate
WARN Using current working directory to re-scaffold the project 
WARN This directory will be cleaned up and all files removed before the re-generation 
INFO Cleaning directory dir=/tmp/test4
INFO Running cleanup 
INFO Running cleanup 
INFO kubebuilder init 
INFO Writing kustomize manifests for you to edit... 
INFO Writing scaffold for you to edit... 
INFO Get controller runtime 
INFO Update dependencies 
Next: define a resource with:
$ kubebuilder create api
INFO Grafana plugin not found, skipping migration 
INFO Auto Update plugin not found, skipping migration 
INFO Deploy-image plugin not found, skipping migration 
INFO Running make manifests 
mkdir -p /tmp/test4/bin
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.19.0
/tmp/test4/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
INFO Running make generate 
/tmp/test4/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
INFO Running make fmt 
go fmt ./...
INFO Running make vet 
go vet ./...
INFO Running make lint-fix 
Downloading github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.4.0
/tmp/test4/bin/golangci-lint run --fix
0 issues.
bash-3.2$ echo $?
0
```

File: pkg/cli/alpha/internal/generate.go [hunk 2]
```diff
@@ -144,14 +144,31 @@ func (opts *Generate) Validate() error {
...
 	}
 
 	return nil
 }
 
+// Helper function to get the PATH of binary.
+func getExecutablePath() (string, error) {
+	execPath, err := os.Executable()
+	if err != nil {
+		return "", fmt.Errorf("kubebuilder executable not found: %w", err)
```
Comment (camilamacedo86) [inline pkg/cli/alpha/internal/generate.go:159]:
```suggestion
		return "", fmt.Errorf("failed to resolve current kubebuilder executable: %w", err)
```

**Review by camilamacedo86 — APPROVED** [review]
/lgtm
/ok-to-test
