### PR TITLE
:book: Fix advice on clients in tests, ensure that book gets tested

### LINKED ISSUE #2128: `make test` fails in docs/book/src/cronjob-tutorial/testdata/project
From HEAD, running `make test` from docs/book/src/cronjob-tutorial/testdata/project fails with:

`SideEffects is required for creating v1 {Mutating,Validating}WebhookConfiguration`

If I fix that by adding the `sideEffects=None` tag to webhooks, it fails with:

`AdmissionReviewVersions is mandatory for v1 {Mutating,Validating}WebhookConfiguration`

If I fix that by adding the `admissionReviewVersions=v1` tag to webhooks, it fails during the e2e test with:

```
2021-04-07T07:50:46.247-0700	ERROR	controller-runtime.manager.controller.cronjob	Reconciler error	{"reconciler group": "batch.tutorial.kubebuilder.io", "reconciler kind": "CronJob", "name": "test-cronjob", "namespace": "default", "error": "field label \".metadata.controller\" not supported for batchv1.Job"}
```

And thats where I got stuck.  Any pointers would be appreciated.  I ran into the "field label not supported" issue on my own project, and don't know how to proceed.

* go version: 1.16
* kubebuilder version (`kubebuilder version`) and scaffolding version (check your `PROJECT` file): kubebuilder 2.3.2, [PROJECT file](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/PROJECT)
* controller-runtime version (check your `go.mod` file): [go.mod](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/go.mod) v0.7.0
* Kubernetes & kubectl versions (just run `kubectl version` against your API server): kubectl v1.16.4

/kind bug

cc @DirectXMan12

### PR DESCRIPTION
**Pull request by DirectXMan12**
As per #2128, the book's `make test` target did not run.  There were two issues at hand:

1. The book was not updated to use the `sideEffects` and `admissionReviewVersions` fields in the `+kubebuilder:webhook` marker (required for v1 webhooks)

2. #2066 incorrectly interpreted advice on test clients and switch the reconciler over to use a live client (the reconciler should always use the manager's client, and in this case has to, because it relies on indicies).

This fixes both those issues, and also adds the book's tests to `make test` so that we don't break this in the future, and makes sure the CI is actually running `make test` instead of a copy of the same actions.

Fixes #2128 
Related to #2066 
Related to #2018

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
@DirectXMan12, 

I am can Ok with this one since seems that it is a blocker for something. 

However, we need to re-generate the book test data samples as we did in the past. We have shell scripts to help with that.

File: docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go [hunk 1]
```diff
@@ -54,7 +54,7 @@ This marker is responsible for generating a mutating webhook manifest.
 The meaning of each marker can be found [here](/reference/markers/webhook.md).
 */
```
Comment (camilamacedo86) [inline docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go:56]: We need to use the helpers to re-generate all. That was the best "manually" solution so far until we find a better way to do that.

**Comment by camilamacedo86** [comment]
/hold

I am working now to push that by updating the full book testdata using the helpers.

**Comment by camilamacedo86** [comment]
@DirectXMan12, 

It is solved here; https://github.com/kubernetes-sigs/kubebuilder/pull/2133

**Review by estroz — APPROVED** [review]
/lgtm

**Comment by DirectXMan12** [comment]
uhhhh, prow?  This is up-to-date afaict.

**Comment by DirectXMan12** [comment]
like, I just ran `git fetch upstream master:master && git rebase master` and I get "current branch is up to date"

**Comment by DirectXMan12** [comment]
hmm...
