### PR TITLE
fix crd validation spec for byte arrays

### LINKED ISSUE #220: Generated CRD validation spec is incorrect for byte arrays
It looks like the generated OpenAPI schema for CRD validation turns a byte array (`[]byte`) into this:

```
items:
  type: byte
type: array
```
This causes validation to fail when trying to create a resource:

```
$kubectl apply -f example.yaml
...
validation failure list:
spec.foo.byteArrayField in body must be of type array: "string"
$
```

To fix this, I have to replace `array` with `string` in the generated CRD definition, though I haven't read the OpenAPI spec in detail to understand if this is the correct fix. Can this be fixed upstream?

I found an explanation [here](http://azure.github.io/autorest/developer/guide/defining-clients-swagger.html#byte-datetime-int-long) that led me to this solution: "To represent byte arrays in the generated code, the property of the OpenAPI definition should have string as its type and byte as its format. This indicates binary data that will be represented as a base64-encoded string in requests and responses."

### PR DESCRIPTION
**Pull request by Liujingfang1**
Fix #220

### CODE REVIEW

File: cmd/internal/codegen/parse/crd.go [hunk 1]
```diff
@@ -292,6 +297,11 @@ func (b *APIs) parseArrayValidation(t *types.Type, found sets.String, comments [
 		Type:  "array",
 		Items: &v1beta1.JSONSchemaPropsOrArray{Schema: &items},
 	}
+	if t.Name.Name == "[]byte" {
+		props.Type = "string"
```
Comment (droot) [inline cmd/internal/codegen/parse/crd.go]: It will be good to include the comment mentioned in the bug here for the context. It will help the reader of the code to understand the context a bit better.
