### PR TITLE
fixed gopkg.toml lookup code in vendor update

### LINKED ISSUE #313: User-added rules in Gopkg.toml not retained when updating vendor
I noticed that user-added rules in `Gopkg.toml` after the comment `# Users add deps lines here` were not retained after running `kubebuilder update vendor` as suggested in http://book.kubebuilder.io/beyond_basics/upgrading_kubebuilder.html. They seemed deleted from `Gopkg.toml`, although `Gopkg.lock` seemed to include them.  This causes IDE such as intellij idea (with the dep plugin) to complain about out of sync for vendored dependencies.

### PR DESCRIPTION
**Pull request by droot**
fixes #313

### CODE REVIEW

File: cmd/kubebuilder/initproject/vendor.go [hunk 1]
```diff
@@ -89,9 +89,20 @@ func depExists() bool {
 	return err == nil
 }
 
+// depManifestExists checks if DepManifestFile exists or not. It will panic
+// if it encounters unknown errors.
 func depManifestExists() bool {
 	_, err := os.Stat(depManifestFile)
-	return os.IsExist(err)
+	if err == nil {
```
Comment (fanzhangio) [inline cmd/kubebuilder/initproject/vendor.go]: The caller `if Update && depManifestExists() {...}` only cares if the file exists not not, so, I am thinking 
```golang
     if  _, err := os.Stat(depManifestFile); err == nil {
             return true
    } 
    return false
```
will be enough. no need to take care of others (but subdivision If statements do can provide more info for debug).

Comment (droot) [reply cmd/kubebuilder/initproject/vendor.go]: I am just being conservative here about not to overwrite the `gopkg.toml` incase of some edge case (like permission to read err or other I/O errors). Its better to warn user about the error and abort vendor update.

Comment (fanzhangio) [reply cmd/kubebuilder/initproject/vendor.go]: Make sense.
