### PR TITLE
🐛 Use correct file name in the comments of `[kind]_types.go`

### LINKED ISSUE #1925: The correct file name should be used in the comments of `[kind]_types.go`
### What broke (please include exact error messages if you can) 
When we use `$ kubebuilder create api`, it generates a file like `[kind]_types.go`. In this file, there is a comment that indicates which file to change when adding a field.

However, the file name in the comment is different from the generated file name. This difference can confuse people.

The example is shown below.

```console
$ kubebuilder create api --group webapp --version v1 --kind Guestbook
Create Resource [y/n]
y
Create Controller [y/n]
y
Writing scaffold for you to edit...
api/v1/guestbook_types.go
controllers/guestbook_controller.go
Running make:
$ make
$PATH/.go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
go build -o bin/manager main.go
kubebuilder create api --group webapp --version v1 --kind Guestbook  6.82s user 5.43s system 153% cpu 7.959 total
```

```console
$ cat api/v1/guestbook_types.go | grep 'Edit Guestbook_types\.go'
        // Foo is an example field of Guestbook. Edit Guestbook_types.go to remove/update
```

In the above example, `Guestbook_types.go` is written in a comment. This is different from the correct file name `guestbook_types.go`.

### What did you expect to happen?  What do you think went wrong? 

A comment should use a correct file name. In the above example, `guestbook_types.go` should be used.

### What versions of software are you using?  

```console
$ go version
go version go1.15.3 darwin/amd64

$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

```console
$ cat go.mod | grep controller-runtime
        sigs.k8s.io/controller-runtime v0.5.0
```

```console
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H114
```

/kind bug

### PR DESCRIPTION
**Pull request by south37**
cf. [The correct file name should be used in the comments of `[kind]_types.go` #1925](https://github.com/kubernetes-sigs/kubebuilder/issues/1925)

## WHAT (= A description of the change)
Fixed the comments in `[kind]_types.go`. The file names in the comments are now correct.

To be more specific, I updated the following files.

- ~~pkg/model/file/mixins.go~~
  - I reverted this change later. cf. https://github.com/kubernetes-sigs/kubebuilder/pull/1927#pullrequestreview-560804582
- pkg/plugins/golang/v2/scaffolds/internal/templates/api/types.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/api/types.go

Then executed `$ make generate`. This execution updated the mock data used in the e2e test.

Fixes #1925

### CODE REVIEW

File: pkg/plugins/golang/v2/scaffolds/internal/templates/api/types.go [hunk 1]
```diff
@@ -75,7 +75,7 @@ type {{ .Resource.Kind }}Spec struct {
 	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
 	// Important: Run "make" to regenerate code after modifying this file
 
-	// Foo is an example field of {{ .Resource.Kind }}. Edit {{ .Resource.Kind }}_types.go to remove/update
+	// Foo is an example field of {{ .Resource.Kind }}. Edit {{ .LoweredResourceKind }}_types.go to remove/update
```
Comment (Adirio) [inline pkg/plugins/golang/v2/scaffolds/internal/templates/api/types.go:78]:
```suggestion
	// Foo is an example field of {{ .Resource.Kind }}. Edit {{ lower .Resource.Kind }}_types.go to remove/update
```

File: pkg/plugins/golang/v3/scaffolds/internal/templates/api/types.go [hunk 2]
```diff
@@ -79,7 +79,7 @@ type {{ .Resource.Kind }}Spec struct {
 	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
 	// Important: Run "make" to regenerate code after modifying this file
 
-	// Foo is an example field of {{ .Resource.Kind }}. Edit {{ .Resource.Kind }}_types.go to remove/update
+	// Foo is an example field of {{ .Resource.Kind }}. Edit {{ .LoweredResourceKind }}_types.go to remove/update
```
Comment (Adirio) [inline pkg/plugins/golang/v3/scaffolds/internal/templates/api/types.go:82]:
```suggestion
	// Foo is an example field of {{ .Resource.Kind }}. Edit {{ lower .Resource.Kind }}_types.go to remove/update
```

**Review by Adirio — CHANGES_REQUESTED** [review]
Templates already have access to the `lower` function, don't need to mess with mixins for this. Revert the changes in `pkg/model/file/mixins.go` and apply the changes below. The resulting `testdata` folder should be the same as in this PR.

**Comment by south37** [comment]
@Adirio 
Thanks for your kind comments! 😄 
I reverted the previous commit ( https://github.com/kubernetes-sigs/kubebuilder/pull/1927/commits/aaba479061cbd225d9ac6cb4309970a2d4b32a7a ) and applied the suggested changes! 💡

**Comment by south37** [comment]
[CI / Verify testdata directory (pull_request)](https://github.com/kubernetes-sigs/kubebuilder/pull/1927/checks?check_run_id=1643199148) seems to have failed due to the fact that it is now 2021 🙈 
Should I add a commit to fix this? Or should I wait until the master is fixed?

```
.
.
.
git diff testdata
diff --git a/testdata/project-v2-addon/api/v1/admiral_types.go b/testdata/project-v2-addon/api/v1/admiral_types.go
index b2a0b75..843fbe3 100644
--- a/testdata/project-v2-addon/api/v1/admiral_types.go
+++ b/testdata/project-v2-addon/api/v1/admiral_types.go
@@ -1,5 +1,5 @@
 /*
-Copyright 2020 The Kubernetes authors.
+Copyright 2021 The Kubernetes authors.
 
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
.
.
.
```

cf. https://github.com/kubernetes-sigs/kubebuilder/runs/1643192980#step:5:1224

**Review by prafull01 — COMMENTED** [review]
@south37 Thanks for your contribution. I have raised a #1929 for fixing the year in testdata. You need to rebase this branch with master once that PR gets merged.

Also, can you please squash all your commits into 1 commit..

**Comment by south37** [comment]
@prafull01
Thanks for your kind comment! 💡 OK, I'll wait for that PR to be merged.
I also squashed all my commits into 1 commit!

**Review by Adirio — APPROVED** [review]
/lgtm

/hold
Holding until the 2021 copyright gets fixed

**Comment by south37** [comment]
https://github.com/kubernetes-sigs/kubebuilder/pull/1929 was merged to master branch, so I rebased this branch! 💡

**Review by prafull01 — APPROVED** [review]

**Comment by south37** [comment]
> You can assign the PR to them by writing `/assign @pwittrock` in a comment when ready.

OK.
/assign @pwittrock

**Review by camilamacedo86 — COMMENTED** [review]
/approve

**Comment by camilamacedo86** [comment]
The 2020/2021 is fixed already it shows fine to get merged. So
/hold cancel

**Comment by south37** [comment]
Thank you for your kind review! 😄
