### PR TITLE
🐛 fix(CLI): Change level for plugin discovery log to debug

### LINKED ISSUE #5597: [CLI] Plugin discovery INFO log always shown in completion
### What broke? What's expected?

When a plugin is discovered at the default path, the INFO log is always output to completion:

```
$ kubebuilder<TAB><TAB>
^[[36mINFO^[[0m Adding external plugin plugin name=foo.acme.io
alpha                                                         (Alpha-stage subcommands)
completion                                                    (Load completions for the specified shell)
create                                                        (Scaffold a Kubernetes API or webhook)
edit                                                          (Update the project configuration)
help                                                          (Help about any command)
init                                                          (Initialize a new project)
version                                                       (Print the kubebuilder version)

$ kubebuilder init<TAB>\$\\E\[36mINFO\\E\[0m\ Adding\ external\ plugin\ plugin\ name=foo.acme.io 
```

### Reproducing this issue

Create a new directory at the default path for plugin discovery.
```
~/.config$ mkdir -p kubebuilder/plugins/foo.acme.io/v2/foo.acme.io
```
Then hit TAB on the `kubebuilder` command or any subcommand to get completion.
The completion will be populated by `^[[36mINFO^[[0m Adding external plugin plugin name=foo.acme.io`.

### KubeBuilder (CLI) Version

master

### PROJECT version

n/a

### Plugin versions

```yaml
n/a
```

### Other versions

n/a

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by vitorfloriano**
This PR changes the log for when a plugin is discovered by Kubebuilder to DEBUG level.

Fixes #5597

### CODE REVIEW

File: pkg/cli/options.go [hunk 1]
```diff
@@ -320,7 +320,7 @@ func DiscoverExternalPlugins(filesystem afero.Fs) (ps []plugin.Plugin, err error
 						return nil, fmt.Errorf("error parsing external plugin version %q: %w", version.Name(), err)
 					}
 
-					slog.Info("Adding external plugin", "plugin name", ep.Name())
+					slog.Debug("Adding external plugin", "plugin name", ep.Name())
```
Comment (camilamacedo86) [inline pkg/cli/options.go:323]: It would be great if when we run any command if we have plugins, external plugins we be aware of.
The external plugins change the behaviour so it is important we know what.

How we could do that?

Comment (vitorfloriano) [reply pkg/cli/options.go:323]: I don't think every command should display that info. 

For example, the current implementation logs that info for commands like `version` and `help`, (and it affects piping commands into others, since it alters the output of the command):

```
$ kubebuilder help
INFO Adding external plugin plugin name=foo.acme.io   <----------------
CLI tool for building Kubernetes extensions and tools.

Usage:
  kubebuilder [flags]
  kubebuilder [command]
```
```
$ kubebuilder version
INFO Adding external plugin plugin name=foo.acme.io  <--------------------
KubeBuilder:          v4.13.2-0.20260410132500-9eaff61e4d5a
Kubernetes:           1.35.0
Git Commit:           9eaff61e4d5a861e56f42bc054cfc93038a09058
Build Date:           2026-04-10T13:25:00Z
Go OS/Arch:           linux/amd64
```
**IMO** if plugins should be installed and explicitly informed by the user in order to be used (they are not set on by default) and the flags that they support are clearly labeled in completion, the users are aware of the plugin's existence and what are its capabilities and we wouldn't need to log that info:

```
$ kubebuilder edit --plugins 
^[[36mINFO^[[0m Adding external plugin plugin name=foo.acme.io
autoupdate.kubebuilder.io/v1-alpha                            (Proposes Kubebuilder scaffold updates via GitHub Actions)
base.go.kubebuilder.io/v4                                     (Default scaffold (go/v4 + kustomize/v2))
deploy-image.go.kubebuilder.io/v1-alpha                       (Scaffolds a CRD+controller to deploy an image-based Operand)
foo.acme.io/v2            <-----------                        (External or custom plugin)
go.kubebuilder.io/v4                                          (Default scaffold (go/v4 + kustomize/v2))
grafana.kubebuilder.io/v1-alpha                               (Generates Grafana Dashboards for metrics)
helm.kubebuilder.io/v2-alpha                                  (Generates a Helm chart for project distribution)
kustomize.common.kubebuilder.io/v2                            (Scaffolds base Kustomize configuration)
```

```
$ kubebuilder edit --plugins foo.acme.io --
--  -----> (For plugin (foo.acme.io/v2): Kubebuilder could not validate this flag with the external plugin. Consult the external plugin documentation for more information.)
--help     (help for edit)
--plugins  (plugin keys to be used for this subcommand execution)
```

```
$ kubebuilder edit --plugins foo.acme.io/v2 --plugins autoupdate.kubebuilder.io/v1-alpha --
--      -------->  (For plugin (foo.acme.io/v2): Kubebuilder could not validate this flag with the external plugin. Consult the external plugin documentation for more information.)
--help             (help for init)
--plugins          (plugin keys to be used for this subcommand execution)
--project-version  (project version)
--use-gh-models    (For plugin (autoupdate.kubebuilder.io/v1-alpha): enable GitHub Models AI summary in the scaffolded workflow (requires GitHub Models permissions))
```

Comment (camilamacedo86) [reply pkg/cli/options.go:323]: I think today is really bad.

But external plugins are called in the chain of all commands. (if used)
So, we probably need to find a nice way to inform that.

**Review by camilamacedo86 — APPROVED** [review]
/lgtm
