### PR TITLE
🐛 (alpha update): Fix --from-version Invalid SemVer error

### LINKED ISSUE #5308: [alpha update] Malformed `--from-version` causes Invalid SemVer error
### What broke? What's expected?

When running `kubebuilder alpha update`, the duplicate "v" prefix in the `--from-version` causes the operation to fail:

```
Error: failed to validate the versions:  
version informed (vv4.9.0) has invalid semantic version. 
Expect: vX.Y.Z (Ex: v4.5.0)
```

### Reproducing this issue

Run `kubebuilder alpha update` without passing the `--from-version` as argument. The command will extract the version from the PROJECT file and prefix a "v" to the `cliVersion` field, which already has a `vX.Y.Z` format, causing an invalid SemVer error.

### KubeBuilder (CLI) Version

Version: cmd.version{KubeBuilderVersion:"v4.10.1", KubernetesVendor:"1.34.1", GitCommit:"$Format:%H$", BuildDate:"1970-01-01T00:00:00Z", GoOs:"unknown", GoArch:"unknown"}

### PROJECT version

3

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v4
- autoupdate.kubebuilder.io/v1-alpha
```

### Other versions

_No response_

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by vitorfloriano**
Running `kubebuilder alpha update` without passing the `--from-version` as argument no longer adds a duplicate "v" prefix to the version extracted from the `PROJECT` file.

Fixes #5308

### CODE REVIEW

File: pkg/cli/alpha/internal/update/prepare_test.go [hunk 1]
```diff
@@ -70,7 +70,7 @@ var _ = Describe("Prepare for internal update", func() {
 		projectFile = filepath.Join(tmpDir, yaml.DefaultPath)
 
 		config.Register(config.Version{Number: 3}, func() config.Config {
-			return &v3.Cfg{Version: config.Version{Number: 3}, CliVersion: "1.0.0"}
+			return &v3.Cfg{Version: config.Version{Number: 3}, CliVersion: "v1.0.0"}
```
Comment (camilamacedo86) [inline pkg/cli/alpha/internal/update/prepare_test.go:73]: CliVersion has not the v.
I think would be nice we have  a test here without v as well.
However, as far I remember the e2e tests have it so 👍 


/lgtm
/approved

**Review by camilamacedo86 — APPROVED** [review]
/lgtm
