### PR TITLE
:bug: fix missing add-to-scheme calls on new API version

### LINKED ISSUE #740: main.go should be updated when creating another CRD with existing Group Kind
Steps to reproduce:
- kubebuilder init --project-version 2 --domain testproject.org --license apache2 --owner "The Kubernetes authors"
- kubebuilder create api --group crew --version v1 --kind Captain --controller=true --resource=true --make=false
- kubebuilder create api --group crew --version v2 --kind Captain --controller=false --resource=true --make=false

We get
```
import (
       ...
	crewv1 "sigs.k8s.io/play-kubebuilder/api/v1"
	// +kubebuilder:scaffold:imports
)
...
func init() {

	crewv1.AddToScheme(scheme)
	// +kubebuilder:scaffold:scheme
}
```

`crewv2` should be there as well.

/kind bug

### PR DESCRIPTION
**Pull request by droot**
The change improves the logic for updating the main.go when
new API/Controller is added to the project.

fixes #740

### CODE REVIEW

File: pkg/scaffold/v2/internal/string_utils.go [hunk 1]
```diff
@@ -115,3 +111,36 @@ func InsertStringsInFile(path string, markerAndValues ...string) error {
 
 	return err
 }
+
+// filterExistingValues removes the marker,value pair for values that already
+// exists in the given reader.
+func filterExistingValues(r io.Reader, markerAndValues ...string) (map[string][]string, error) {
```
Comment (mengqiy) [inline pkg/scaffold/v2/internal/string_utils.go]: IIRC each item in `markerAndValues` must NOT be a multi-line string.
Please add a comment for it.

File: pkg/scaffold/v2/main.go [hunk 2]
```diff
@@ -45,6 +47,67 @@ func (m *Main) GetInput() (input.Input, error) {
...
+}
+
+// MainUpdateOptions contains info required for wiring an API/Controller in
+// main.go.
+type MainUpdateOptions struct {
+	// Project contains info about the project
+	Project *input.ProjectFile
+
+	// Resource is the resource being added
+	Resource *resource.Resource
```
Comment (mengqiy) [inline pkg/scaffold/v2/main.go]: `resource.Resource` comes from `"sigs.k8s.io/kubebuilder/pkg/scaffold/v1/resource"`.
IMO a `v2` package should not depend on a `v1` package. IOW, `resource` should be moved to a shared package.

File: pkg/scaffold/v2/internal/string_utils.go [hunk 3]
```diff
@@ -33,44 +33,40 @@ import (
...
-			if strings.TrimSpace(line) == strings.TrimSpace(v) {
-				// since value already exist, so avoid duplication
-				delete(mvPairs, m)
-			}
-			if strings.Contains(line, m) {
-				_, err := buf.WriteString(v)
-				if err != nil {
-					return nil, err
+		for marker, vals := range markerVals {
+			if strings.Contains(line, marker) {
```
Comment (DirectXMan12) [inline pkg/scaffold/v2/internal/string_utils.go]: I'm not sure `strings.Contains` is correct here -- that means that `// +foo:marker:bar` would match `foo:marker`, which seems incorrect.

File: pkg/scaffold/v2/internal/string_utils.go (hunk 1 above)
Comment (DirectXMan12) [inline pkg/scaffold/v2/internal/string_utils.go]: this should just take in a map

File: pkg/scaffold/v2/internal/string_utils.go (hunk 3 above)
Comment (droot) [reply pkg/scaffold/v2/internal/string_utils.go]: Good catch. Added strict comparison.

File: pkg/scaffold/v2/internal/string_utils.go (hunk 1 above)
Comment (droot) [reply pkg/scaffold/v2/internal/string_utils.go]: Done.

Comment (droot) [reply pkg/scaffold/v2/internal/string_utils.go]: Done.

File: pkg/scaffold/v2/main.go (hunk 2 above)
Comment (droot) [reply pkg/scaffold/v2/main.go]: > IMO a v2 package should not depend on a v1 package.

Thats debatable :). If you don't feel strongly about it, I would keep this refactor out of scope for this PR.

File: pkg/scaffold/v2/internal/string_utils.go [hunk 4]
```diff
@@ -33,44 +33,40 @@ import (
 // v1 will be inserted below the lines containing m1 string and v2 will be inserted
 // below line containing m2 string.
 func insertStrings(r io.Reader, markerAndValues ...string) (io.Reader, error) {
```
[the remark this answers is not in the document]
Comment (droot) [reply pkg/scaffold/v2/internal/string_utils.go]: I have enhanced one of the tests to include multiple strings. Let me know if there is any particular test you think we should add.

**Comment by droot** [comment]
> we shouldn't be re-calling inflect all over the place, re-implementing package naming etc. We're going to have to burn some of this down soon

I agree.

File: pkg/scaffold/v2/main.go (hunk 2 above)
Comment (mengqiy) [reply pkg/scaffold/v2/main.go]: IMHO when I change the scaffolding under v1 package, I wouldn't expect v2 scaffolding being affected. Otherwise, it makes it hard to reasoning.

I did a quick check, it seems we have quite some places in v2 that are importing v1 packages. It makes me sad. 
The change here is not the first one doing it. I'm OK to leave it in a separate PR. :)

Comment (droot) [reply pkg/scaffold/v2/main.go]: I took a look at the use of v1.Resource in v2 scaffolding and it turns out data to represent a resource is entirely same when it comes to v1/v2 scaffolding, so if we try to completely isolate v1/v2, we will end up duplicating the structure. Now for sharing the same data structure, one could move v1.Resource to a common pkg, but that has the same affect of importing v1 pkg in v2 because one has to reason about the usage of that shared structure in across v1/v2 scaffolding.
WDYT ?

File: pkg/scaffold/v2/internal/string_utils.go [hunk 5]
```diff
@@ -115,3 +111,32 @@ func InsertStringsInFile(path string, markerAndValues ...string) error {
...
+		}
+	}
+	if err := scanner.Err(); err != nil {
+		return err
+	}
+	return nil
+}
+
+// removeElementAt removes the element at index i from a.
+func removeElementAt(a []string, i int) []string {
```
Comment (mengqiy) [inline pkg/scaffold/v2/internal/string_utils.go]: This function can be one single line according to [this](https://github.com/golang/go/wiki/SliceTricks#delete).

File: pkg/scaffold/v2/main.go (hunk 2 above)
Comment (mengqiy) [reply pkg/scaffold/v2/main.go]: Reorganize the code into `common`, `v1` and `v2` can make it easier to maintain the scaffolding the code in long term. But if adding change something in `common`, contributors still need to reason the usage of share structure across v1 and v2 scaffolding.

We can keep the scope of this PR as is, and have these thoughts in mind when we reorganizing the code in the followup PR.

File: pkg/scaffold/v2/internal/string_utils.go (hunk 5 above)
Comment (droot) [reply pkg/scaffold/v2/internal/string_utils.go]: Thanks for the tip. Done :)

File: pkg/scaffold/v2/internal/string_utils.go [hunk 6]
```diff
@@ -29,51 +28,48 @@ import (
...
+// line line containing marker string. So for ex. in insertStrings(r, {'m1':
+// [v1], 'm2': [v2]})
 // v1 will be inserted below the lines containing m1 string and v2 will be inserted
 // below line containing m2 string.
-func insertStrings(r io.Reader, markerAndValues ...string) (io.Reader, error) {
-	if len(markerAndValues)%2 != 0 {
-		return nil, fmt.Errorf("invalid marker and value pairs")
-	}
+func insertStrings(r io.Reader, markerAndValues map[string][]string) (io.Reader, error) {
+	// reader clone is needed since we will be reading twice from the given reader
```
[the remark this answers is not in the document]
Comment (droot) [reply pkg/scaffold/v2/internal/string_utils.go]: Yes, we are still reading twice, so this is needed.

File: pkg/scaffold/v2/internal/string_utils.go [hunk 7]
```diff
@@ -29,51 +28,48 @@ import (
 )
 
 // insertStrings reads content from given reader and insert string below the
-// line line containing marker string. So for ex. in insertStrings(r, m1, v1, m2, v2)
+// line line containing marker string. So for ex. in insertStrings(r, {'m1':
```
[the remark this answers is not in the document]
Comment (droot) [reply pkg/scaffold/v2/internal/string_utils.go]: Done :)

File: pkg/scaffold/v2/main.go (hunk 2 above)
Comment (droot) [reply pkg/scaffold/v2/main.go]: Ack.
