### PR TITLE
📖  Fix generation of markers based on controller-tools 

### LINKED ISSUE #4044: CRD marker reference is broken
### What broke? What's expected?

https://book.kubebuilder.io/reference/markers/crd.html shows
Bildschirmfoto 2024-07-24 um 14 04 57

### Reproducing this issue

_No response_

### KubeBuilder (CLI) Version

docs

### PROJECT version

_No response_

### Plugin versions

_No response_

### Other versions

_No response_

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by marlapativ**
# Description:

This PR fixes the issue https://github.com/kubernetes-sigs/kubebuilder/issues/4044

## Fixes #4044

Due to changes in the commit: https://github.com/kubernetes-sigs/kubebuilder/commit/bf42d50683595602edd28d56549ee33ef2df30cb, the build for the markerdocs application was failing.

For future reference, the error is being ignored in the build part of markerdocs app. 
https://github.com/kubernetes-sigs/kubebuilder/blob/f97e8734409a804e831d9863e625b18cbb08862d/docs/book/markerdocs.sh#L23C3-L24C1

I wasn't sure if the script was supposed to be fixed or not as the build failure is ignored.

# Motivation:

The documentation for the CRD Generation screen in broken
image

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
@marlapativ

Kudos +1000 🥇 

I have no time to check this one and I would be able to do only in the weekend
Huge thanks for find out the issue and came up with this PR

Well DONE 

Your help was very appreciate.
We just need to do a cherry-pick against the branch book-v4 
So that, we can fix it in prod. Could you please push this one?

thank you!!!


/lgtm
/approved
/ok-to-test

File: docs/book/utils/markerdocs/main.go [hunk 1]
```diff
@@ -176,8 +176,7 @@ func (p MarkerDocs) Process(input *plugin.Input) error {
 			}
 		}
 
-		if _, err = _, _ = fmt.Fprintf(content, "</dl></div>")
```
Comment (camilamacedo86) [inline docs/book/utils/markerdocs/main.go:179]: I see where/when it brokes :-( 
That was my fault

**Comment by marlapativ** [comment]
@camilamacedo86 

I apologize as I didn't understand what you mean by cherry-pick to branch `book-v4`

Should I raise a new pull request to `book-v4` cherry-picking this commit?
