### PR TITLE
pkg/controller: re-add to the queue failed reconcile keys

### LINKED ISSUE #224: Events are not re-enqueued
The GenericController does not add an event back to the queue if the Reconciler function returns an error and its totally depending of the re-sync interval to reprocess an item which is not what I might expect to do.

### PR DESCRIPTION
**Pull request by jhernandezb**
fixes #224

### CODE REVIEW

File: pkg/controller/controller_test.go [hunk 1]
```diff
@@ -476,6 +479,34 @@ var _ = Describe("GenericController", func() {
 		})
 	})
 
+	Describe("Retrying events with errored Reconcile calls", func() {
```
Comment (droot) [inline pkg/controller/controller_test.go]: may be: "Re-queue an item when reconcile returns error" ?

**Comment by jhernandezb** [comment]
commits squashed
